### ISSUE TITLE
How to update a rendered view

### ISSUE THREAD

**Issue by digitalrinaldo** [dagrejs/dagre-d3#17]
Thanks for the well done library. I am trying to update some labels on nodes I have displayed. I have updated the node label and want to redraw it. I am a bit lost as to where to look, D3, SVG of the graphlib dagre-D3 uses.

**Comment by randallto** [comment]
Using dagre in angularjs it seems to be persisting information from a previous chart drawing.  You can reload the chart and first remove the entire svg element, re-add it and give it a new id even. The second loading of the same chart in the dagre seems to think the svg width is twice as big as previous and the height is half the size. I am drawing horizontal in instead of vertical.  The nodes width space grows while the height shrinks. The causes a distorted chart.  You hit 5f and all is good again.

**Comment by cpettitt** [comment]
@randallto Sounds like a new ticket to me. It also needs a simple repro case.
