### ISSUE TITLE
Version of d3 is outdated

### ISSUE THREAD

**Issue by nothingismagick** [dagrejs/dagre-d3#375]
We just noticed that there is a discrepency between the version of d3 used in dagre and the one used by mermaid. I am not deep enough into dagre to know if there is a fundamental reason to use version 4 of d3 - or if merely updating the dep to v5 is ok. This might also be a case where deferring to a peerDependency as mentioned in #359 would resolve this. (My guess is that there are too many projects depending on dagre and that might actually be a breaking change...)

Here is the issue where we are tracking it at mermaid:

https://github.com/knsv/mermaid/issues/990

**Comment by gordonwoodhull** [comment]
I don't know this library well, but I use dagre and know d3 well. I don't know about problems with projects depending on dagre-d3, but I have verified that dagre-d3 builds and tests OK with D3v5. (FWIW I also verified dagre-d3-renderer.)

There are very few [breaking changes](https://github.com/d3/d3/blob/master/CHANGES.md) between D3v3 and D3v4, and they would mostly break web applications rather than other libraries.

Anyway, I submitted #376 if it helps you any.
