### ISSUE TITLE
On Firefox 24: getBBox is not a function

### ISSUE THREAD

**Issue by eugeneia** [dagrejs/dagre-d3#78]
I get this error after following the example setup using d3 and dagre-d3 (dagre-d3 v0.2.9).

`TypeError: labelSvg.node(...).getBBox is not a function @ http://mr.gy/scripts/dagre-d3.js:571`

**Comment by divergentdave** [comment]
FYI to anyone else who runs into this, you can get around it by using `createElementNS()` instead of `createElement()` and passing the namespace URI http://www.w3.org/2000/svg. In my case, I was creating the &lt;svg&gt; element dynamically, but I had to do this with `document.createElementNS("http://www.w3.org/2000/svg", "svg")`.

**Comment by myfreeweb** [comment]
Just hit this. Turns out Firefox also throws this error when the SVG is hidden by something like `display:none`… or… being in a closed `<details>` dropdown! Dangit Firefox >_<
